### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [delayel06/youarethehero#2]
It seems you may have forgotten to add a free license to the project. I suggest AGPLv3 :)

**Comment by delayel06** [comment]
Could you tell me what that license does?  I am afraid my work may be 
taken if I put a license.

**Comment by pizzamaker** [comment]
Basically AGPLv3 says that people are free to reuse, modify and republish this program, but their versions also need to be under the AGPLv3 terms. This ensures that people don't take your work to make proprietary programs on top of it :)

**Comment by delayel06** [comment]
The thing is, I want people to be able to see how I made my work, but still keep all rights copyrighted for my work, as well as let them "fork" it, so that license wouldn't work.
I found at https://help.github.com/articles/open-source-licensing/ that if you don't include a license, that is exactly what happens.

**Comment by challsted** [comment]
Does this still need to be kept open? Looks like delayel06 is happy with his default license.
